name: facturacuellosuazo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Librerías esenciales para Bilexis AutoNCF NATIVO:
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.6.0
  shared_preferences: ^2.2.0
  excel: ^3.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# 📲 Configuración de iconos de lanzamiento (Launcher Icons)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

# 💦 Configuración del Splash Screen Nativo
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/app_icon.png"
  android: true
  ios: true

# 🛠️ Sección de configuración de Flutter
flutter:
  uses-material-design: true

  # Declaración oficial de Assets para el proyecto
  assets:
    - assets/icon/app_icon.png
    - web/favicon.png